apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.sftpserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      initContainers:
      - name: {{ .Release.Name }}-init
        image: {{ .Values.sftpserver.init_image }}
        imagePullPolicy: "Always"
        env:
        - name: SFTP_USERS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-sftpusers
              key: SFTP_USERS
        - name: azurestorageaccountname
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-filestore
              key: azurestorageaccountname
        - name: azurestorageaccountkey
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-filestore
              key: azurestorageaccountkey        
      containers:
      - name: {{ .Release.Name }}-sftp
        image: {{ .Values.sftpserver.image }}
        imagePullPolicy: "Always"
        env:
        - name: SFTP_USERS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-sftpusers
              key: SFTP_USERS        
        - name: azurestorageaccountname
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-filestore
              key: azurestorageaccountname
        - name: azurestorageaccountkey
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-filestore
              key: azurestorageaccountkey        
        resources:
          requests:
            cpu: .5
            memory: 250M
          limits:
            cpu: 1
            memory: 500M
        ports:
        - name: sftp
          containerPort: 22
          protocol: TCP

        # mount upload path for every user
        volumeMounts:
        {{- range .Values.sftpserver.users }}
        - name: {{ (split ":" . )._0 }}
          mountPath: /home/{{ (split ":" . )._0 }}/upload
        {{- end }}

      volumes:
      {{- range .Values.sftpserver.users }}
      - name: {{ (split ":" . )._0 }}
        persistentVolumeClaim:
          claimName: {{ (split ":" . )._0 }}    
      {{- end }}
