apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
{{- if .Values.service.private }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
{{- end }}    
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-deployment  
  ports:
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22