name: kubeapi-reverseproxy helm chart push to ACR
on:
  push:
    paths:
      - "Application/kubeapi-reverseproxy/**"
      - ".github/workflows/kubeapi-reverseproxy.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Push helm chart to ACR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az acr helm push -n rabickelmasteraks $GITHUB_WORKSPACE/Application/kubeapi-reverseproxy