name: kubeapi-reverseproxy helm chart push to ACR
on:
  push:
    paths:
      - "Application/kubeapi-reverseproxy/**"
      - ".github/workflows/kubeapi-reverseproxy-chart-publish.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package --version "$(date +"%Y%m").$GITHUB_RUN_NUMBER" $GITHUB_WORKSPACE/Application/kubeapi-reverseproxy

      - name: Push helm chart to ACR
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az acr helm push -n rabickelmasteraks kubeapi-reverseproxy-"$(date +"%Y%m").$GITHUB_RUN_NUMBER".tgz --force