name: Payment Api Build
on:
  push:
    paths:
      - "Application/PaymentAPI/app/**"
      - ".github/workflows/paymentapi.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az acr build -r rabickelmasteraks -t paymentapi:$GITHUB_RUN_ID -t paymentapi:$GITHUB_SHA $GITHUB_WORKSPACE/Application/PaymentAPI
