name: Payment Api Build
on:
  push:
    paths:
      - "Application/PaymentAPI/app/**"
      - ".github/workflows/paymentapi.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v1
        with:
          service_principal: ${{ secrets.ARM_CLIENT_ID }}
          service_principal_password: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant: ${{ secrets.ARM_TENANT_ID }}
          registry: rabickelmasteraks
          repository: paymentapi
          image: paymentapi
          folder: ../../Application/PaymentAPI
